version: "3.9"
services:
  airbnb-front:
    container_name: airbnb-front
    build:
      context: ./airbnb-front
      dockerfile: Dockerfile
    restart: always
    privileged: true
    tty: true
    working_dir: /var/www
    volumes:
       - ./airbnb-front:/var/www
       - /var/www/node_modules
    expose:
      - "3000"
    networks:
      - airbnb-network
  airbnb-back:
    container_name: airbnb-back
    build:
      context: ./airbnb-back
      dockerfile: Dockerfile
    restart: always
    privileged: true
    tty: true
    depends_on:
      - airbnb-mongodb
    working_dir: /var/www
    volumes:
       - ./airbnb-back:/var/www
       - /var/www/node_modules
    expose:
      - "3000"
    networks:
      - airbnb-network

  airbnb-mongodb:
    image: mongo:latest
    container_name: airbnb-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - dbdata:/data/db
    networks:
      - airbnb-network

  airbnb-nginx:
    image: nginx:1.22-alpine
    container_name: airbnb-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8080:8080"
      - "3000:3000"
    depends_on: 
      - airbnb-back
      #- airbnb-front
    volumes:
      #- ./airbnb-front/public:/app
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - airbnb-network

networks:
  airbnb-network:
    driver: bridge

volumes:
  dbdata:
    driver: local